-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 18:28:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema studio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema studio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studio` DEFAULT CHARACTER SET utf8 ;
USE `studio` ;

-- -----------------------------------------------------
-- Table `studio`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `telnum` VARCHAR(17) NOT NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`typeofcloth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`typeofcloth` (
  `name` VARCHAR(45) NOT NULL,
  `days` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`master` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telnum` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `master_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `typeofcloth_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_master_idx` (`master_id` ASC) VISIBLE,
  INDEX `fk_order_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_order_typeofcloth1_idx` (`typeofcloth_name` ASC) VISIBLE,
  CONSTRAINT `fk_order_master`
    FOREIGN KEY (`master_id`)
    REFERENCES `studio`.`master` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `studio`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_typeofcloth1`
    FOREIGN KEY (`typeofcloth_name`)
    REFERENCES `studio`.`typeofcloth` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`material` (
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`hardware` (
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`material_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`material_order` (
  `quantity` INT NOT NULL,
  `material_name` VARCHAR(45) NOT NULL,
  `order_id` INT NOT NULL,
  INDEX `mo_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `mo_material_name_idx` (`material_name` ASC) VISIBLE,
  CONSTRAINT `mo_order_id_idx`
    FOREIGN KEY (`order_id`)
    REFERENCES `studio`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `mo_material_name_idx`
    FOREIGN KEY (`material_name`)
    REFERENCES `studio`.`material` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio`.`hardware_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio`.`hardware_order` (
  `quantity` INT NOT NULL,
  `hardware_name` VARCHAR(45) NOT NULL,
  `order_id` INT NOT NULL,
  INDEX `ho_hardware_name_idx` (`hardware_name` ASC) VISIBLE,
  INDEX `ho_order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `ho_hardware_name_idx`
    FOREIGN KEY (`hardware_name`)
    REFERENCES `studio`.`hardware` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ho_order_id_idx`
    FOREIGN KEY (`order_id`)
    REFERENCES `studio`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
